services:
  client:
    build:
      context: ./frontend
      args: 
        NEXT_PUBLIC_API_BASE_URL: /server
    container_name: client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: /server
    depends_on:
      - server

  server:
    build:
      context: ./server
      args:
        DATABASE_URL: mysql://root:example_password@mysql:3307/bezkoder_db
    container_name: server
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://root:example_password@mysql:3307/bezkoder_db
      JWT_SECRET: "fvaGFIUDEWgwti974tglow24cdxsghnjmkrasetgzryr7x6ruyn5htbevs4y5ew"
      SECRET_KEY: "5feFV0nZSglXiFJj"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: bezkoder_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
