version: '3.8'

services:
  client:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    container_name: client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    depends_on:
      - server
    networks:
      - my-network

  server:
    build:
      context: ./server
      args:
        DATABASE_URL: mysql://root:example_password@mysql:3306/bezkoder_db
        JWT_SECRET: fvaGFIUDEWgwti974tglow24cdxsghnjmkrasetgzryr7x6ruyn5htbevs4y5ew
        FRONT_END: http://localhost:3000
        SECRET_KEY: 5feFV0nZSglXiFJj
    container_name: server
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - my-network
    environment:
      DATABASE_URL: mysql://root:example_password@mysql:3306/bezkoder_db
      JWT_SECRET: fvaGFIUDEWgwti974tglow24cdxsghnjmkrasetgzryr7x6ruyn5htbevs4y5ew
      SECRET_KEY: 5feFV0nZSglXiFJj
    volumes:
      - ./server/.env:/app/.env  # Monta o arquivo .env dentro do container
      - ./server/prisma:/app/prisma  # Monta o diretório prisma dentro do container

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: bezkoder_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql_data:
    driver: local

networks:
  my-network:
    driver: bridge
