services:
  server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:example_password@mysql:3307/bezkoder_db
    
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: bezkoder_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local
